set-option -g prefix M-a

unbind C-b

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-S-Up resize-pane -U
bind -n M-S-Down resize-pane -D

bind \ split-window -h
bind - split-window -v

unbind '"'
unbind %

set -sg escape-time 10

set -g default-terminal "screen-256color"
set -g history-limit 100000
set -g status-justify left
set -g status-fg colour13 
set -g status-bg colour55 
set -g status-left "#h> "
set -g status-right "%d/%m/%y @ %r"

setw -g window-status-fg colour13
setw -g window-status-bg colour55

if-shell "hostname | grep -v scornful" \
  "set -g status-fg colour255; \
   set -g status-bg colour238; \
   setw -g window-status-fg colour255; \
   setw -g window-status-bg colour238;"
