#!/usr/bin/env sh

dotfiles=$(pwd)

# Symlink all the things.
mkdir -p ~/.config/

ln -sf $(ls -d $dotfiles/source/.config/*) ~/.config/
ln -sf $(find $dotfiles/source/ -maxdepth 1 -name '.*' -type f) ~/

# Install the base packages.
case $(uname) in
  'Linux')
    sudo apt update
    sudo apt install build-essential -y

    for item in $(sed -n -E "s/brew \"(.+)\"/\1/p" $dotfiles/Brewfile); do
      sudo apt install $item -y
    done

    fish_path=$(which fish)
    ;;
  'Darwin')
    if ! command -v brew &> /dev/null; then
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    PATH=$PATH:/opt/homebrew/bin:/usr/local/bin

    brew bundle --file=$dotfiles/Brewfile

    brew_prefix=$(brew config | sed -n -E "s/HOMEBREW_PREFIX: (.+)/\1/p")
    fish_path="${brew_prefix}/bin/fish"

    if ! grep -q "${fish_path}" /etc/shells; then
      echo "${fish_path}" | sudo tee -a /etc/shells
    fi
esac

# Switch to fish
chsh -s $fish_path
