vim.api.nvim_set_hl(0, "Comment", { ctermfg = 242 })
vim.api.nvim_set_hl(0, "Error", { bold = true, ctermfg = 255, ctermbg = 9 })
vim.api.nvim_set_hl(0, "IncSearch", { underline = true, ctermfg = 255, ctermbg = 238})
vim.api.nvim_set_hl(0, "LineNr", { ctermfg = 242 })
vim.api.nvim_set_hl(0, "MatchParen", { underline = true, ctermfg = 255, ctermbg = 238 })
vim.api.nvim_set_hl(0, "Pmenu", { ctermfg = 250, ctermbg = none })
vim.api.nvim_set_hl(0, "Search", { underline = true, ctermfg = 255, ctermbg = 238 })
vim.api.nvim_set_hl(0, "SpellBad", { bold = true, ctermfg = 255, ctermbg = 9 })
vim.api.nvim_set_hl(0, "SpellCap", { bold = true, ctermfg = 255, ctermbg = 56 })
vim.api.nvim_set_hl(0, "StatusLine", { ctermbg = none })
vim.api.nvim_set_hl(0, "User1", { ctermfg = 225 })
vim.api.nvim_set_hl(0, "User2", { bold = true, ctermfg = 255 })
vim.api.nvim_set_hl(0, "VertSplit", { cterm = none, ctermfg = 237 })
