vim.api.nvim_set_hl(0, "Error", { cterm = bold, ctermfg = 255, ctermbg = 9 })
vim.api.nvim_set_hl(0, "IncSearch", { cterm = underline, ctermfg = 255, ctermbg = 238})
vim.api.nvim_set_hl(0, "LineNr", { ctermfg = 242})
vim.api.nvim_set_hl(0, "MatchParen", { cterm = underline, ctermfg = 255, ctermbg = 238 })
vim.api.nvim_set_hl(0, "Pmenu", { ctermfg = 250, ctermbg = none })
vim.api.nvim_set_hl(0, "Search", { cterm = underline, ctermfg = 255, ctermbg = 238 })
vim.api.nvim_set_hl(0, "SpellBad", { cterm = bold, ctermfg = 255, ctermbg = 9 })
vim.api.nvim_set_hl(0, "SpellCap", { cterm = bold, ctermfg = 255, ctermbg = 56 })
vim.api.nvim_set_hl(0, "StatusLine", { cterm = bold, ctermfg = 7, ctermbg = none })
vim.api.nvim_set_hl(0, "StatusLineNC", { cterm = none, ctermfg = 250, ctermbg = none })
vim.api.nvim_set_hl(0, "TabLineFill", { cterm = none })
vim.api.nvim_set_hl(0, "Tabline", { ctermbg = none, ctermfg = 12 })
vim.api.nvim_set_hl(0, "User1", { ctermfg = 255, ctermbg = none })
vim.api.nvim_set_hl(0, "User2", { ctermfg = 10, ctermbg = none })
vim.api.nvim_set_hl(0, "User3", { ctermfg = 243, ctermbg = none })
vim.api.nvim_set_hl(0, "VertSplit", { cterm = none, ctermfg = 237 })
