vim.cmd.colorscheme("vim")

vim.api.nvim_set_hl(0, "Added", { fg = "#60ff17", bg = none })
vim.api.nvim_set_hl(0, "Changed", { fg = "#4da3ff", bg = none })
vim.api.nvim_set_hl(0, "Comment", { fg = "#777777" })
vim.api.nvim_set_hl(0, "Delete", { fg = "#ff2200", bg = none })
vim.api.nvim_set_hl(0, "Error", { bold = true, fg = "#ff2200" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#b091ff", bg = none })
vim.api.nvim_set_hl(0, "IncSearch", { link = "Search" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#666666" })
vim.api.nvim_set_hl(0, "lualine_a_buffers_active", { bold = true, fg = "#CCBCFB" })
vim.api.nvim_set_hl(0, "MatchParen", { underline = true, fg = "#ffffff", bg = none })
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#ffffff", bg = "#000000" })
vim.api.nvim_set_hl(0, "PmenuSel", { bold = true, fg = "#ffffff", bg = "#000000" })
vim.api.nvim_set_hl(0, "Search", { underline = true, fg = "#ffffff", bg = "#6eadff" })
vim.api.nvim_set_hl(0, "SignColumn", { bg = none })
vim.api.nvim_set_hl(0, "Special", { fg = "#888888" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#ff22aa", bold = true })
vim.api.nvim_set_hl(0, "StatusLine", { bg = none })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = none })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = none })
vim.api.nvim_set_hl(0, "Title", { link = "Special" })
vim.api.nvim_set_hl(0, "Type", { fg = "#FFF36B", bold = true })
vim.api.nvim_set_hl(0, "VertSplit", { fg = "#444444", bg = none })
