vim.api.nvim_set_hl(0, "Comment", { fg = 242 })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = none, ctermfg = 2, fg = 2 })
vim.api.nvim_set_hl(0, "DiffChange", { bg = none, ctermfg = 12, fg = 12 })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = none, ctermfg = 9, fg = 9 })
vim.api.nvim_set_hl(0, "Error", { bold = true, ctermfg = 255, ctermbg = 9, fg = 255, bg = 9 })
vim.api.nvim_set_hl(0, "IncSearch", { underline = true, ctermfg = 255, ctermbg = 238, fg = 255, bg = 238})
vim.api.nvim_set_hl(0, "LineNr", { ctermfg = 242, fg = 242 })
vim.api.nvim_set_hl(0, "MatchParen", { underline = true, ctermfg = 255, ctermbg = 238, fg = 255, bg = 238 })
vim.api.nvim_set_hl(0, "Pmenu", { ctermfg = 250, fg = 250, bg = none })
vim.api.nvim_set_hl(0, "Search", { underline = true, ctermfg = 255, ctermbg = 238, fg = 255, bg = 238 })
vim.api.nvim_set_hl(0, "SignColumn", { bg = none })
vim.api.nvim_set_hl(0, "SpellBad", { bold = true, ctermfg = 255, ctermbg = 9, fg = 255, bg = 9 })
vim.api.nvim_set_hl(0, "SpellCap", { bold = true, ctermfg = 255, ctermbg = 56, fg = 255, bg = 56 })
vim.api.nvim_set_hl(0, "StatusLine", { bg = none })
vim.api.nvim_set_hl(0, "User1", { ctermfg = 225, fg = 225 })
vim.api.nvim_set_hl(0, "User2", { bold = true, ctermfg = 255, fg = 255 })
vim.api.nvim_set_hl(0, "VertSplit", { cterm = none, ctermfg = 237, fg = 237 })
